# **Data Wrangling Lab**

this week we are  performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

Import pandas module.

In [ ]:
import pandas as pd
import numpy as np

Load the dataset into a dataframe.

In [ ]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [ ]:

df.duplicated().sum()
# use this code if who are duplicates
# df[df.duplicated()]

154

In [ ]:
# number of duplicated value in column Respondent
df['Respondent'].duplicated().sum()

154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [ ]:


df.drop_duplicates(inplace = True)

In [ ]:
# after removing number of rows
df.shape[0]

11398

In [ ]:
# After removing the duplicate rows, how many unique rows are there in the column Respondent?
df['Respondent'].nunique()

11398

Verify if duplicates were actually dropped.

In [ ]:

df.duplicated().sum()

0

## Finding Missing values

Find the missing values for all columns.

In [ ]:

df.isnull().sum()

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ...
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64

In [ ]:
# After removing the duplicate rows, how many blank rows are there under the column EdLevel?

df['EdLevel'].isnull().sum()

112

In [ ]:
#After removing the duplicate rows, how many rows are missing under the column Country?
df['Country'].isnull().sum()

0

Find out how many rows are missing in the column 'WorkLoc'

In [ ]:

df['WorkLoc'].isnull().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [ ]:

df['WorkLoc'].notnull().sum()

# or use this
df['WorkLoc'].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

In [ ]:
# What is the majority category under the column Employment?
df['Employment'].value_counts()

Employed full-time    10968
Employed part-time      430
Name: Employment, dtype: int64

In [ ]:
# Under the column " UndergradMajor", which category has the minimum number of rows
df['UndergradMajor'].value_counts()

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

In [ ]:

df["ConvertedComp"].describe() # it have outlier so go for median in case to replace ConvertedComp mising value

count    1.058200e+04
mean     1.315967e+05
std      2.947865e+05
min      0.000000e+00
25%      2.686800e+04
50%      5.774500e+04
75%      1.000000e+05
max      2.000000e+06
Name: ConvertedComp, dtype: float64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [ ]:
#make a note of the majority value here, for future reference

df['WorkLoc'].value_counts().sort_values(ascending = False).head(1)

Office    6806
Name: WorkLoc, dtype: int64

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [ ]:

df['WorkLoc'].fillna("Office", inplace = True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [ ]:

df['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [ ]:
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

In [ ]:
# your code goes here

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

In [ ]:

df['NormalizedAnnualCompensation'] = df[['CompFreq','CompTotal']].apply(lambda x: x['CompTotal']*12 if x['CompFreq']=='Monthly' else x['CompTotal']*52 if x['CompFreq']=='Weekly' else x['CompTotal'], axis = 1)
df['NormalizedAnnualCompensation']
# in apply function if axis = 1 then row wise and  in series wise (as raw = false by default in apply parameter) data will go to x(input) , and all columns name will act as this series
# index and if want access them then do like this x[column 1], x[column2] they can act like different varriable (you can also say lambada is applying row wise here). u can have as much variable as there are number of column
# now if in apply function axis = 0 then data will go column wise and in series , now all real index will act as index name of this series (you can also say is apying columnwise here)

0         61000.0
1        138000.0
2         90000.0
3        348000.0
4         90000.0
           ...
11547    130000.0
11548     74400.0
11549    105000.0
11550     80000.0
11551         NaN
Name: NormalizedAnnualCompensation, Length: 11398, dtype: float64

In [ ]:
df['CompFreq'].nunique()

3

In [ ]:
# After removing the duplicate rows, how many respondents are being paid yearly?
df.where(df['CompFreq'] == 'Yearly')['Respondent'].count()

6073

In [ ]:
#What is the median NormalizedAnnualCompensation?
df['NormalizedAnnualCompensation'].median()

100000.0

Exporting final data as csv file

In [ ]:
df.to_csv("M2 survey file after wrangling.csv", index = False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')